name: your_project_name
description: Generatore Codici QR Demo.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  image: ^4.0.15
  path_provider: ^2.0.12
  qr_flutter: ^4.0.0
  http: ^0.13.5
  share_plus: ^3.0.5
  universal_html: ^2.0.9
  cloud_firestore: ^4.4.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  dio: ^4.0.0
  firebase_auth: ^4.2.8
  flutterfire_ui: ^0.4.3+20
  firebase_analytics: ^10.1.3
  firebase_performance: ^0.9.0+13
  firebase_crashlytics: ^3.0.14
  firebase_ui_auth: ^1.1.13
  cloud_functions: ^4.0.10
  selectable: ^0.2.11

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
